create table if not exists banks (
  id bigint generated by default as identity primary key,
  name text,
  mrr numeric
);

create table if not exists promotions (
  id bigint generated by default as identity primary key,
  bank_id bigint references banks(id),
  promo_name text,
  rate_year1 numeric,
  rate_year2 numeric,
  rate_year3 numeric,
  final_rate_formula text,
  conditions text
);

create table if not exists profiles (
  id bigint generated by default as identity primary key,
  name text,
  age int,
  salary numeric,
  bonus numeric,
  other_income numeric,
  debt numeric
);

insert into banks (name,mrr) values ('ธนาคาร A',6.5),('ธนาคาร B',6.3),('ธนาคาร C',6.7);

insert into promotions (bank_id,promo_name,rate_year1,rate_year2,rate_year3,final_rate_formula,conditions)
values (1,'โปร A1',3.25,4.00,5.50,'-MRR 2%','รายได้ขั้นต่ำ 15000');
